### ISSUE TITLE
在8.0.0版本上使用qq的聊天界面净化会闪退

### ISSUE THREAD

**Issue by luoawai123** [zpp0196/QQPurify#69]
在8.0.0版本上使用qq的聊天界面净化会闪退

**Comment by zhoushangren** [comment]
+1 版本是8.0.0.4000

**Comment by zpp0196** [comment]
能提供一下日志吗

**Comment by zhoushangren** [comment]
```
2019-06-19 17:16:34.615/? A/QQPurify: logLevel: ERROR
2019-06-19 17:16:34.665/? E/QQPurify: null class
java.lang.IllegalArgumentException: null class
	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
	at d.a.a.b.h.a(SourceFile:11)
	at d.a.a.b.h.d(SourceFile:3)
	at d.a.a.b.k.d(SourceFile:2)
	at me.zpp0196.qqpurify.hook.a.e.hideFont(SourceFile:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:2)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
	at EdHooker_.hook(Unknown Source:142)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
	at EdHooker_.hook(Unknown Source:141)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-19 17:16:34.739/? E/QQPurify: null class
java.lang.IllegalArgumentException: null class
	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
	at d.a.a.b.h.a(SourceFile:11)
	at d.a.a.b.h.d(SourceFile:3)
	at d.a.a.b.k.d(SourceFile:2)
	at me.zpp0196.qqpurify.hook.ChatHook.hideAvatar(SourceFile:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:1)
	at me.zpp0196.qqpurify.hook.ChatHook.b(SourceFile:1)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
	at EdHooker_.hook(Unknown Source:142)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
	at EdHooker_.hook(Unknown Source:141)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-19 17:16:34.842/? E/QQPurify: null class
java.lang.IllegalArgumentException: null class
	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
	at d.a.a.b.h.a(SourceFile:11)
	at d.a.a.b.h.d(SourceFile:3)
	at d.a.a.b.k.d(SourceFile:2)
	at me.zpp0196.qqpurify.hook.ExtensionHook.openFlashAsPic(SourceFile:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:1)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
	at EdHooker_.hook(Unknown Source:142)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
	at EdHooker_.hook(Unknown Source:141)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by zpp0196** [comment]
> ```
> 2019-06-19 17:16:34.615/? A/QQPurify: logLevel: ERROR
> 2019-06-19 17:16:34.665/? E/QQPurify: null class
> java.lang.IllegalArgumentException: null class
> 	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
> 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
> 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
> 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
> 	at d.a.a.b.h.a(SourceFile:11)
> 	at d.a.a.b.h.d(SourceFile:3)
> 	at d.a.a.b.k.d(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.a.e.hideFont(SourceFile:2)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
> 	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
> 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
> 	at EdHooker_.hook(Unknown Source:142)
> 	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
> 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
> 	at EdHooker_.hook(Unknown Source:141)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
> 	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
> 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6863)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 2019-06-19 17:16:34.739/? E/QQPurify: null class
> java.lang.IllegalArgumentException: null class
> 	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
> 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
> 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
> 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
> 	at d.a.a.b.h.a(SourceFile:11)
> 	at d.a.a.b.h.d(SourceFile:3)
> 	at d.a.a.b.k.d(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.ChatHook.hideAvatar(SourceFile:2)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:1)
> 	at me.zpp0196.qqpurify.hook.ChatHook.b(SourceFile:1)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
> 	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
> 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
> 	at EdHooker_.hook(Unknown Source:142)
> 	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
> 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
> 	at EdHooker_.hook(Unknown Source:141)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
> 	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
> 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6863)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 2019-06-19 17:16:34.842/? E/QQPurify: null class
> java.lang.IllegalArgumentException: null class
> 	at com.elderdrivers.riru.edxp.yahfa.core.HookMain.findMethod(HookMain.java:132)
> 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:252)
> 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
> 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:239)
> 	at d.a.a.b.h.a(SourceFile:11)
> 	at d.a.a.b.h.d(SourceFile:3)
> 	at d.a.a.b.k.d(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.ExtensionHook.openFlashAsPic(SourceFile:4)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.a(SourceFile:24)
> 	at me.zpp0196.qqpurify.hook.base.BaseHook.b(SourceFile:1)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:31)
> 	at me.zpp0196.qqpurify.hook.InitializeHook.a(SourceFile:2)
> 	at me.zpp0196.qqpurify.hook.m.a(SourceFile:5)
> 	at d.a.a.b.g.afterHookedMethod(SourceFile:2)
> 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
> 	at EdHooker_.hook(Unknown Source:142)
> 	at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
> 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
> 	at EdHooker_.hook(Unknown Source:141)
> 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
> 	at com.elderdrivers.riru.edxp.yahfa.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:83)
> 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6863)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```

这个是edxp的问题

**Comment by zhoushangren** [comment]
@zpp0196 更新edxp解决了 谢谢！

**Comment by luoawai123** [comment]
在太极上还是闪退

**Comment by luoawai123** [comment]
2019-06-19 20:28:06.469/? A/QQPurify: logLevel: ERROR
错误日志什么都没有，但是在太极中使用qq聊天界面净化还是闪退

**Comment by luoawai123** [comment]
@zpp0196

**Comment by funusb** [comment]
> 2019-06-19 20:28:06.469/? A/QQPurify: logLevel: ERROR
> 错误日志什么都没有，但是在太极中使用qq聊天界面净化还是闪退

你这样给我说我也没办法解决，我自己用的也是太极就没问题

**Comment by zpp0196** [comment]
> 2019-06-19 20:28:06.469/? A/QQPurify: logLevel: ERROR
> 错误日志什么都没有，但是在太极中使用qq聊天界面净化还是闪退

你这样我也没办法解决啊，我自己用的也是太极就没问题

**Comment by luoawai123** [comment]
那这么说，你用的太极是什么版本呢？qq呢，我太极版本是5.2.0，qq是8.0.0，看看是不是太极的问题

**Comment by luoawai123** [comment]
@zpp0196

**Comment by zpp0196** [comment]
> 那这么说，你用的太极是什么版本呢？qq呢，我太极版本是5.2.0，qq是8.0.0，看看是不是太极的问题

和你一样太极5.2.0，QQ8.0.0的人很多，基本都没有问题
